{{- if and .Values.vitess.enabled (not .Values.vitess.existingSecret) .Values.vitess.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirador-core.fullname" . }}-vitess
  labels:
    {{- include "mirador-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.vitess.password | quote }}
{{- end }}

