{{- if and (or ((index .Values "vitess-external").enabled) ((index .Values "vitess-embedded").enabled)) (not (index (index .Values "vitess-external") "existingSecret")) (index (index .Values "vitess-external") "password") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mirador-core.fullname" . }}-vitess
  labels:
    {{- include "mirador-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ (index (index .Values "vitess-external") "password") | quote }}
{{- end }}
