{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-mirador-env" (include "mirador-core.fullname" .)) .Values.secrets.name }}
  labels:
    {{- include "mirador-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secrets.data.JWT_SECRET }}
  {{- if . }}
  JWT_SECRET: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secrets.data.LDAP_PASSWORD }}
  {{- if . }}
  LDAP_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secrets.data.SMTP_PASSWORD }}
  {{- if . }}
  SMTP_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secrets.data.REDIS_PASSWORD }}
  {{- if . }}
  REDIS_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.secrets.data.VM_PASSWORD }}
  {{- if . }}
  VM_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}

