services:
  # VictoriaMetrics Suite
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    pull_policy: if_not_present
    container_name: victoriametrics
    network_mode: host
    volumes:
      - vmdata:/victoria-metrics-data
    command:
      - --storageDataPath=/victoria-metrics-data

  victorialogs:
    image: victoriametrics/victoria-logs:latest
    pull_policy: if_not_present
    container_name: victorialogs
    network_mode: host
    volumes:
      - vldata:/victoria-logs-data
    command:
      - --storageDataPath=/victoria-logs-data

  victoriatraces:
    image: victoriametrics/victoria-traces:latest
    pull_policy: if_not_present
    container_name: victoriatraces
    network_mode: host
    volumes:
      - vtdata:/victoria-traces-data
    command:
      - --storageDataPath=/victoria-traces-data

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    pull_policy: if_not_present
    container_name: otel-collector
    network_mode: host
    command: ["--config", "/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    # On Linux, uncomment to allow host.docker.internal resolution
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "/otelcol-contrib", "--version"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Valkey (single-node)
  valkey:
    image: valkey/valkey:latest
    pull_policy: if_not_present
    container_name: mirador-valkey
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -h 127.0.0.1 ping | grep -q PONG"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Weaviate (DEV): local vector DB for schema store
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.32.8
    pull_policy: if_not_present
    container_name: weaviate
    network_mode: host
    restart: unless-stopped
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      DEFAULT_VECTORIZER_MODULE: "none"
      QUERY_DEFAULTS_LIMIT: "25"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      AUTOSCHEMA_ENABLED: "false"
      LOG_LEVEL: "debug"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/v1/.well-known/ready"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - weavdata:/var/lib/weaviate

  # MIRADOR-CORE (builds natively for host arch)
  mirador-core:
    build:
      context: ../..
      dockerfile: Dockerfile
    # If you prefer to pull a published image instead of building, comment out the build: block above
    # and set the image tag:
    # image: platformbuilds/mirador-core:v2.1.3
    container_name: mirador-core
    network_mode: host
    restart: unless-stopped
    depends_on:
      valkey:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    # On Linux, uncomment to allow host.docker.internal resolution
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    environment:
      # App basics
      - PORT=8010
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - CONFIG_PATH=/configs/config.development.yaml
      - AUTH_ENABLED=false
      # Bulk CSV upload max size (bytes). Alternatively set BULK_UPLOAD_MAX_MIB
      - BULK_UPLOAD_MAX_BYTES=5242880

      # Weaviate (DEV)
      - WEAVIATE_HOST=127.0.0.1
      - WEAVIATE_PORT=8080
      - WEAVIATE_SCHEME=http
      - WEAVIATE_ENABLED=true
      - WEAVIATE_USE_OFFICIAL=false

      # Point to local Victoria services (same compose network)
      - VM_ENDPOINTS=http://127.0.0.1:8428
      - VL_ENDPOINTS=http://127.0.0.1:9428
      - VT_ENDPOINTS=http://127.0.0.1:10428

      # Valkey (single-node)
      - VALKEY_CACHE_NODES=127.0.0.1:6379
      - CACHE_TTL=300

      # Auth + RBAC (dev)
      - JWT_SECRET=development-secret-key-not-for-production
      - RBAC_ENABLED=true

    healthcheck:
      test: ["CMD", "/mirador-core", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 12
    volumes:
      - ../../configs:/configs:ro
      - bleve-data:/var/lib/mirador/bleve

volumes:
  vmdata: {}
  vldata: {}
  vtdata: {}
  weavdata: {}
  bleve-data: {}
