version: '3.7'
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    ports:
      - 8428:8428 # Metrics UI/API
    volumes:
      - ./vmdata:/victoria-metrics-data
    command:
      - --storageDataPath=/victoria-metrics-data

  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    ports:
      - 9428:9428 # Logs UI/API
    volumes:
      - ./vldata:/victoria-logs-data
    command:
      - --storageDataPath=/victoria-logs-data

  victoriatraces:
    image: victoriametrics/victoria-traces:latest
    container_name: victoriatraces
    ports:
      - 8429:8429 # Traces UI/API
    volumes:
      - ./vtdata:/victoria-traces-data
    command:
      - --storageDataPath=/victoria-traces-data
