# Images
images:
  etcd: bitnami/etcd:3.5.12
  vtctld: vitess/vtctld:v18.0.2
  vtgate: vitess/vtgate:v18.0.2
  vttablet: vitess/vttablet:v18.0.2

topology:
  cell: zone1
  keyspace: mirador
  # List of shards for the keyspace. Examples: ["0"] or ["-80","80-"]
  shards:
    - "0"

resources: {}

persistence:
  size: 5Gi
  # Optional: set a specific StorageClass for vttablet PVCs
  # storageClass: standard

service:
  vtgate:
    type: ClusterIP
    port: 15306

# etcd subchart controls
etcd:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    size: 5Gi
    # Optional: set a specific StorageClass for etcd PVCs
    # storageClass: standard

vtgate:
  replicas: 2
  resources: {}
  # Override vtgate executable path if your image differs
  command: "/vt/bin/vtgate"

vttablet:
  replicasPerShard: 2 # 1 PRIMARY + (replicasPerShard-1) REPLICA
  resources: {}
  # Override vttablet executable path if your image differs
  command: "/vt/bin/vttablet"
  mysql:
    extraArgs: []
    initDb:
      enabled: true
      # Some Vitess versions do not support passing the init SQL via
      # vttablet flag. Leave this false unless your image supports it.
      useFlag: false
      sql: |
        -- Minimal MySQL configuration for Vitess tablets
        SET GLOBAL sql_mode='NO_ENGINE_SUBSTITUTION';
        SET GLOBAL innodb_strict_mode=OFF;
        SET GLOBAL enforce_gtid_consistency=ON;
        SET GLOBAL gtid_mode=ON;
        SET GLOBAL log_bin_trust_function_creators=ON;

# Optional: provide a minimal vtctld viper config to silence
# "Config File \"vtconfig\" Not Found" warnings. When enabled,
# a ConfigMap is mounted at /vt/vtconfig.yaml and the container
# working directory is set to /vt so vtctld discovers it.
vtctld:
  # Override vtctld executable path if your image differs
  command: "/vt/bin/vtctld"
  config:
    enabled: false
    data: |
      # vtctld configuration (optional)
      # This file can be left empty to silence the
      # "Config File \"vtconfig\" Not Found" warning.
      # Add key: value pairs if you want to override defaults.

# Backups via vtctldclient Backup (requires vttablet backup flags configured)
backup:
  enabled: false
  schedule: "0 2 * * *" # daily at 02:00
  vtctldClientImage: vitess/vtctldclient:v18.0.2
  # additional arguments to vtctldclient (e.g., TLS options)
  extraArgs: []
