apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaviate.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "weaviate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "weaviate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

