{{- if .Values.backup.enabled }}
{{- range $idx, $shard := .Values.topology.shards }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vitess-minimal.fullname" $ }}-backup-{{ $idx }}
spec:
  schedule: {{ $.Values.backup.schedule | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "vitess-minimal.name" $ }}
            app.kubernetes.io/component: backup
        spec:
          restartPolicy: OnFailure
          containers:
            - name: vtctldclient
              image: {{ $.Values.backup.vtctldClientImage }}
              args:
                - "--server={{ include \"vitess-minimal.fullname\" $ }}-vtctld:15000"
                {{- range $a := $.Values.backup.extraArgs }}
                - {{ $a | quote }}
                {{- end }}
                - "Backup"
                - "{{ $.Values.topology.keyspace }}/{{ $shard }}"
{{- end }}
{{- end }}

