apiVersion: v1
kind: Service
metadata:
  name: {{ include "vitess-minimal.fullname" . }}-vtctld
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 15000
  selector:
    app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
    app.kubernetes.io/component: vtctld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vitess-minimal.fullname" . }}-vtctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
      app.kubernetes.io/component: vtctld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
        app.kubernetes.io/component: vtctld
    spec:
      containers:
        - name: vtctld
          image: {{ .Values.images.vtctld }}
          args:
            - "--topo_implementation=etcd2"
            - "--topo_global_server_address={{ include "vitess-minimal.etcdClientHost" . }}:2379"
            - "--topo_global_root=/vitess/global"
          ports:
            - containerPort: 15000
