apiVersion: v1
kind: Service
metadata:
  name: {{ include "vitess-minimal.fullname" . }}-vtctld
{{- if .Values.vtctld.config.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitess-minimal.fullname" . }}-vtctld-config
data:
  vtconfig.yaml: |
{{ .Values.vtctld.config.data | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 15000
  selector:
    app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
    app.kubernetes.io/component: vtctld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vitess-minimal.fullname" . }}-vtctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
      app.kubernetes.io/component: vtctld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "vitess-minimal.name" . }}
        app.kubernetes.io/component: vtctld
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: vtctld
          image: {{ include "vitess-minimal.renderImage" (dict "image" .Values.images.vtctld "Values" .Values) }}
          # Some vtctld images may not define an ENTRYPOINT. Set command explicitly
          # so Kubernetes executes the vtctld binary and passes Helm-provided args.
          command:
            - "/vt/bin/vtctld"
          args:
            - "--topo_implementation=etcd2"
            - "--topo_global_server_address={{ include "vitess-minimal.etcdClientHost" . }}:2379"
            - "--topo_global_root=/vitess/global"
            - "--syslog=false"
          {{- if .Values.vtctld.config.enabled }}
          workingDir: /vt
          volumeMounts:
            - name: vtctld-config
              mountPath: /vt
              readOnly: true
          {{- end }}
          ports:
            - containerPort: 15000
      {{- if .Values.vtctld.config.enabled }}
      volumes:
        - name: vtctld-config
          configMap:
            name: {{ include "vitess-minimal.fullname" . }}-vtctld-config
      {{- end }}
