# Development Environment Configuration
environment: development
port: 8080
log_level: debug

database:
  victoria_metrics:
    endpoints:
      - "http://localhost:8481"
    timeout: 10000
  victoria_logs:
    endpoints:
      - "http://localhost:9428"
    timeout: 10000
  victoria_traces:
    endpoints:
      - "http://localhost:10428"
    timeout: 10000

grpc:
  predict_engine:
    endpoint: "localhost:9091"
    models: ["isolation_forest", "lstm_trend"]
    timeout: 10000
  rca_engine:
    endpoint: "localhost:9092"
    correlation_threshold: 0.8
    timeout: 10000
  alert_engine:
    endpoint: "localhost:9093"
    timeout: 10000

auth:
  ldap:
    enabled: false
  oauth:
    enabled: false
  rbac:
    enabled: true
    admin_role: "admin"
  jwt:
    expiry_minutes: 480 # 8 hours for development

cache:
  nodes:
    - "localhost:6379"
  ttl: 60 # Shorter TTL for development

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://127.0.0.1:3000"

integrations:
  slack:
    enabled: false
  ms_teams:
    enabled: false
  email:
    enabled: false

websocket:
  enabled: true
  max_connections: 100
  ping_interval: 10

monitoring:
  enabled: true
  prometheus_enabled: true
  tracing_enabled: true

uploads:
  # Configurable bulk CSV upload limit (bytes). Default is 5 MiB if omitted.
  bulk_max_bytes: 5242880
