name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.23.12
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.12'

      - name: Download modules
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
