name: govulncheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vuln:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.23.12
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.12'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        working-directory: public/mirador-core
        run: govulncheck ./...
